application: css2json
version: wilson
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /static
  static_dir: static
  expiration: "1d"
